# Read the Docs configuration file for Sphinx
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Set up build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    # Clone tomviz repository before building
    pre_build:
      - git clone https://github.com/OpenChemistry/tomviz.git /tmp/tomviz
      - pip install /tmp/tomviz/tomviz/python
      - python scripts/generate_operator_docs.py --local /tmp/tomviz/tomviz/python --output docs/operators

# Python configuration
python:
  install:
    # Install documentation dependencies
    - requirements: requirements.txt
